name: pte_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'  # More flexible version constraint

dependencies:
  flutter:
    sdk: flutter

  # Updated packages (critical fixes)
  syncfusion_flutter_calendar: ^29.1.38  # Latest stable from 23.x series
  syncfusion_flutter_charts: ^29.1.38    # Must match calendar version
  google_generative_ai: ^0.4.7          # Major upgrade from 0.1.0
  file_picker: ^10.1.2                  # Fixes platform warnings
  intl: ^0.18.1                         # Required for localization
  csv: ^6.0.0                          # Added for parsing CSV responses
  path_provider: ^2.1.1                # Added for file storage
  permission_handler: ^11.1.0
  device_info_plus: ^10.1.1
  cookie_jar: ^4.0.6  # Add this line
  # Maintained packages with latest stable versions
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.5.1
  provider: ^6.1.2
  dio: ^5.4.0
  animate_do: ^4.0.1
  font_awesome_flutter: ^10.6.0
  flutter_animate: ^4.5.0
  rflutter_alert: ^2.0.4
  country_picker: ^2.0.27
  flutter_map_marker_popup: ^6.1.2
  geolocator: ^10.1.0
  table_calendar: ^3.0.9
  fl_chart: ^0.70.2
  curved_navigation_bar: ^1.0.3
  flutter_native_splash: ^2.3.7
  awesome_dialog: ^3.2.1                # Upgraded from 2.0.0
  giffy_dialog: ^2.0.0
  google_fonts: ^6.2.1  
  line_icons: ^2.0.0
  flutter_chat_ui: ^1.1.9
  googleapis_auth: ^1.2.0
  googleapis: ^11.2.1
  flutter_neumorphic: ^3.2.0
  web_socket_channel: ^2.4.0
  mime: ^1.0.0
  http_parser: ^4.0.0
  quickalert: ^1.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  pdf: ^3.11.0
  printing: ^5.12.0
  url_launcher: ^6.3.0                 
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^19.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  open_file: ^3.3.2
  hive_generator: ^2.0.0
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - assets/images/prologic.png
    - assets/images/prologic_feed.png
    - assets/images/homebackground.jpg
    - assets/images/default_avatar.png
    - assets/illustrations/login.jpg
    - assets/illustrations/register.jpg
    - assets/illustrations/available.png
    - assets/illustrations/reserved.png
    - assets/illustrations/upcoming.png
    - assets/illustrations/vehicles.jpg
    - assets/illustrations/rooms.png
    - assets/illustrations/forgot.png
    - assets/illustrations/validate.png
    - assets/ptechatbot-nwgf-5e693e141c47.json

flutter_native_splash:
  color: "#0632A1"
  image: assets/images/prologic.png
  android: true
  ios: true